[lcd4linux @ 2006-01-21 13:26:43 by reinelt] Logitech G-15 keyboard LCD driver from Dave Ingram
git-svn-id: https://ssl.bulix.org/svn/lcd4linux/trunk@618 3ae390bd-cb1e-0410-b409-cd5a39f66f1f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -869,10 +869,10 @@ Optional Packages:
                           (try 'all,\!<driver>' if your shell complains...)
                           possible drivers are:
                           BeckmannEgle, BWCT, CrystalFontz, Curses, Cwlinux,
-                          HD44780, LCDLinux, LCDTerm, LPH7508, LUIse, M50530,
-                          MatrixOrbital, MilfordInstruments, Noritake, NULL,
-                          PNG, PPM, RouterBoard, Sample, serdisplib, SimpleLCD,
-                          T6963, Trefon, USBLCD, WincorNixdorf, X11
+                          G15, HD44780, LCDLinux, LCDTerm, LPH7508, LUIse,
+                          M50530, MatrixOrbital, MilfordInstruments, Noritake,
+                          NULL, PNG, PPM, RouterBoard, Sample, serdisplib,
+                          SimpleLCD, T6963, Trefon, USBLCD, WincorNixdorf, X11
   --with-plugins=<list>   choose which plugins to compile.
                           type --with-plugins=list for a list
                           of avaible plugins
@@ -6190,6 +6190,7 @@ for driver in $drivers; do
          CRYSTALFONTZ="yes"
          CURSES="yes"
          CWLINUX="yes"
+         G15="yes"
          HD44780="yes"
 	 LCDLINUX="yes"
          LCDTERM="yes"
@@ -6226,6 +6227,9 @@ for driver in $drivers; do
          ;;
       Cwlinux)
          CWLINUX=$val
+         ;;
+      G15)
+         G15=$val
          ;;
       HD44780)
          HD44780=$val
@@ -6378,6 +6382,22 @@ cat >>confdefs.h <<\_ACEOF
 #define WITH_CWLINUX 1
 _ACEOF
 
+fi
+
+if test "$G15" = "yes"; then
+   if test "$has_usb" = "true"; then
+      GRAPHIC="yes"
+      DRIVERS="$DRIVERS drv_G15.o"
+      DRVLIBS="$DRVLIBS -lusb"
+
+cat >>confdefs.h <<\_ACEOF
+#define WITH_G15 1
+_ACEOF
+
+   else
+      { echo "$as_me:$LINENO: WARNING: usb.h not found: G15 driver disabled" >&5
+echo "$as_me: WARNING: usb.h not found: G15 driver disabled" >&2;}
+   fi
 fi
 
 if test "$HD44780" = "yes"; then
