picoLCDGraphic driver by Nicu Pavel added
git-svn-id: https://ssl.bulix.org/svn/lcd4linux/trunk@881 3ae390bd-cb1e-0410-b409-cd5a39f66f1f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1345,8 +1345,8 @@ Optional Packages:
                           BeckmannEgle, BWCT, CrystalFontz, Curses, Cwlinux,
                           G15, HD44780, LCD2USB LCDLinux, LCDTerm, LPH7508,
                           LUIse, M50530, MatrixOrbital, MilfordInstruments,
-                          Noritake, NULL, PNG, PPM, Pertelian, picoLCD, RouterBoard,
-                          Sample, serdisplib, SimpleLCD, st2205, T6963, Trefon,
+                          Noritake, NULL, PNG, PPM, Pertelian, picoLCD, picoLCDGraphic,
+                          RouterBoard, Sample, serdisplib, SimpleLCD, st2205, T6963, Trefon,
                           USBLCD, USBHUB, WincorNixdorf, X11
   --with-plugins=<list>   choose which plugins to compile.
                           type --with-plugins=list for a list
@@ -7556,6 +7556,7 @@ for driver in $drivers; do
          NULL="yes"
          PERTELIAN="yes"
          PICOLCD="yes"
+	 PICOLCDGRAPHIC="yes"
          PNG="yes"
          PPM="yes"
          ROUTERBOARD="yes"
@@ -7636,6 +7637,10 @@ for driver in $drivers; do
       picoLCD)
          PICOLCD=$val
          ;;
+      picoLCDGraphic)
+         PICOLCDGRAPHIC=$val
+         ;;
+
       PNG)
          PNG=$val
          ;;
@@ -7807,6 +7812,7 @@ if test "$HD44780" = "yes"; then
    PARPORT="yes"
    I2C="yes"
    GPIO="yes"
+   KEYPAD="yes"
    DRIVERS="$DRIVERS drv_HD44780.o"
 
 cat >>confdefs.h <<\_ACEOF
@@ -7996,6 +8002,25 @@ _ACEOF
    else
       { echo "$as_me:$LINENO: WARNING: usb.h not found: picoLCD driver disabled" >&5
 echo "$as_me: WARNING: usb.h not found: picoLCD driver disabled" >&2;}
+   fi
+fi
+
+if test "$PICOLCDGRAPHIC" = "yes"; then
+   if test "$has_usb" = "true"; then
+      TEXT="yes"
+      GRAPHIC="yes"
+      GPIO="yes"
+      SERIAL="yes"
+      LIBUSB="yes"
+      DRIVERS="$DRIVERS drv_picoLCDGraphic.o"
+
+cat >>confdefs.h <<\_ACEOF
+#define WITH_PICOLCDGRAPHIC 1
+_ACEOF
+
+   else
+      { echo "$as_me:$LINENO: WARNING: usb.h not found: picoLCDGraphic driver disabled" >&5
+echo "$as_me: WARNING: usb.h not found: picoLCDGraphic driver disabled" >&2;}
    fi
 fi
 
