[lcd4linux @ 2006-08-08 19:35:21 by reinelt] USBHUB driver from Ernst Bachmann
git-svn-id: https://ssl.bulix.org/svn/lcd4linux/trunk@683 3ae390bd-cb1e-0410-b409-cd5a39f66f1f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1307,7 +1307,7 @@ Optional Packages:
                           LUIse, M50530, MatrixOrbital, MilfordInstruments,
                           Noritake, NULL, PNG, PPM, RouterBoard, Sample,
                           serdisplib, SimpleLCD, T6963, Trefon, USBLCD,
-                          WincorNixdorf, X11
+                          USBHUB, WincorNixdorf, X11
   --with-plugins=<list>   choose which plugins to compile.
                           type --with-plugins=list for a list
                           of avaible plugins
@@ -7603,6 +7603,7 @@ for driver in $drivers; do
          SIMPLELCD="yes"
          T6963="yes"
          Trefon="yes"
+	 USBHUB="yes"
          USBLCD="yes"
 	 WINCORNIXDORF="yes"
          X11="yes"
@@ -7684,6 +7685,9 @@ for driver in $drivers; do
          ;;
       Trefon)
          Trefon=$val
+         ;;
+      USBHUB)
+         USBHUB=$val
          ;;
       USBLCD)
          USBLCD=$val
@@ -8063,6 +8067,22 @@ _ACEOF
    else
       { echo "$as_me:$LINENO: WARNING: usb.h not found: Trefon driver disabled" >&5
 echo "$as_me: WARNING: usb.h not found: Trefon driver disabled" >&2;}
+   fi
+fi
+
+if test "$USBHUB" = "yes"; then
+   if test "$has_usb" = "true"; then
+      GPIO="yes"
+      DRIVERS="$DRIVERS drv_USBHUB.o"
+      LIBUSB="yes"
+
+cat >>confdefs.h <<\_ACEOF
+#define WITH_USBHUB 1
+_ACEOF
+
+   else
+      { echo "$as_me:$LINENO: WARNING: usb.h not found: USB-Hub driver disabled" >&5
+echo "$as_me: WARNING: usb.h not found: USB-Hub driver disabled" >&2;}
    fi
 fi
 
