[lcd4linux @ 2006-01-18 11:49:48 by reinelt] adopted to lcd-linux-0.9.2
git-svn-id: https://ssl.bulix.org/svn/lcd4linux/trunk@614 3ae390bd-cb1e-0410-b409-cd5a39f66f1f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5921,7 +5921,8 @@ done
 
 # check for LCD-Linux
 
-for ac_header in linux/lcd-linux.h
+
+for ac_header in linux/lcd-linux.h linux/hd44780.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -6066,7 +6067,7 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
 _ACEOF
  has_lcd_linux="true"
 else
-  has_lcd_linux="false"
+  has_lcd_linux="false"; break
 fi
 
 done
@@ -6402,8 +6403,8 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
    else
-      { echo "$as_me:$LINENO: WARNING: lcd-linux.h not found: LCD-Linux driver disabled" >&5
-echo "$as_me: WARNING: lcd-linux.h not found: LCD-Linux driver disabled" >&2;}
+      { echo "$as_me:$LINENO: WARNING: linux/lcd-linux.h or linux/hd44780.h not found: LCD-Linux driver disabled" >&5
+echo "$as_me: WARNING: linux/lcd-linux.h or linux/hd44780.h not found: LCD-Linux driver disabled" >&2;}
    fi
 fi
 
