driver for GX series lcd from Matrix Orbital by Abbas Kosan
git-svn-id: https://ssl.bulix.org/svn/lcd4linux/trunk@988 3ae390bd-cb1e-0410-b409-cd5a39f66f1f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7695,7 +7695,7 @@ for driver in $drivers; do
          D4D="yes"
          EA232graphic="yes"
          G15="yes"
-         GLCD2USB="yes"
+         GLCD2USB="no"
          HD44780="yes"
 	 IRLCD="yes"
          LCD2USB="yes"
@@ -7706,6 +7706,7 @@ for driver in $drivers; do
          LUISE="yes"
          M50530="yes"
          MATRIXORBITAL="yes"
+         MATRIXORBITALGX="yes"
          MILINST="yes"
          NORITAKE="yes"
          NULL="yes"
@@ -7787,6 +7788,9 @@ for driver in $drivers; do
          ;;
       MatrixOrbital)
          MATRIXORBITAL=$val
+         ;;
+      MatrixOrbitalGX)
+         MATRIXORBITALGX=$val
          ;;
       MilfordInstruments)
          MILINST=$val
@@ -8156,6 +8160,23 @@ cat >>confdefs.h <<\_ACEOF
 #define WITH_MATRIXORBITAL 1
 _ACEOF
 
+fi
+
+if test "$MATRIXORBITALGX" = "yes"; then
+    if test "$has_usb" = "true"; then
+        GRAPHIC="yes"
+        SERIAL="yes"
+        LIBUSB="yes"
+        DRIVERS="$DRIVERS drv_MatrixOrbitalGX.o"
+
+cat >>confdefs.h <<\_ACEOF
+#define WITH_MATRIXORBITALGX 1
+_ACEOF
+
+    else
+        { echo "$as_me:$LINENO: WARNING: usb.h not found: MatrixOrbitalGX driver disabled" >&5
+echo "$as_me: WARNING: usb.h not found: MatrixOrbitalGX driver disabled" >&2;}
+    fi
 fi
 
 if test "$MILINST" = "yes"; then
